services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    networks:
      - appnet

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
