services:
  backend:
    build: ./backend
    container_name: ft_backend
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    container_name: ft_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
